const TIPO_VALOR = {
	ENTERO: 'VAL_ENTERO',
	ID: 'VAL_ID',
	CADENA: 'VAL_CADENA',
}

const TIPO_OPERACION = {
	SUMA: 'OP_SUMA',
	RESTA: 'OP_RESTA',
	MULTIPLICACION: 'OP_MULTIPLICACION',
	DIVISION: 'OP_DIVISION',

}

const TIPO_INSTRUCCION = {
	IMPRIMIR: 'IN_IMPRIMIR',
}

//Exportar constantes

module.exports.TIPO_INSTRUCCION = TIPO_INSTRUCCION;
module.exports.TIPO_OPERACION = TIPO_OPERACION;
module.exports.TIPO_VALOR = TIPO_VALOR;